<?php



function detectLanguage() {
    $lang = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? 'en';
    $lang = substr($lang, 0, 2); // 取前兩位，例如 zh / en / fr
    return $lang;
}

$lang = detectLanguage();

switch ($lang) {
    case 'zh':
        $strings = zhcn();
        break;
    default:
        $strings = enus();
}

function zhcn() {
    return [
        'username' => '用户名',
        'password' => '密码',
        'login' => '登录',
        'logout' => '退出登录',
        'logout_all' => '一键销毁所有会话',
        'accountsettings' => '账户设定',
        'email' => '邮箱',
        'phonenumber' => '手机号',
        'optional' => '选填',
        'register' => '注册',
        'verifyemail' => '验证你的邮箱',
        'verificationcode' => '验证码',
        'submit' => '提交',
        'noaccount' => '没有账号？',
        'haveacc' => '已有账号？',
        'warning' => '警告',
        'invalidcredential' => '你的凭据已失效',
        'emergencyblock' => "紧急冻结",
        'notification' => '通知',
        'notifications' => '通知',
        'loginsuccessful' => '登录成功',
        'passwordchanged' => '密码已修改',
        'idchanged' => 'ID已被更改',
        'emailchanged' => '邮箱已修改',
        'phonenumberchanged' => '手机号已修改',
        'contactadmintoedit' => '请联系管理员修改此项',
        'notchanged' => '未更改',
        'adminportal' => '管理员门户',
        '2fa' => '2FA验证码',
        'errortitle' => '嗷呜…… 出错力',
        'PKCE_required' => '要不回去原来的站点再点一遍登录试试',
        'totheportal' => '前往账户控制台',
        'wechatcode' => '微信验证码',
        'wechat2farequired' => '账户已开启微信两步验证，请正确输入微信验证码',
        'learnmore' => '了解更多',
        'dashboard' => '仪表盘',
        'clientcontrol' => 'Client管理',
        'systemutil' => '系统工具',
        'usercontrol' => '用户管理',
        'mgmt' => '管理',
        'createnewclient' => '创建新的Client',
        'requirepkce' => '要求 PKCE',
        'create' => '创建',
        'oneperline' => '每行一个',
        'registeredclients' => '现存的Client',
        'status' => '状态',
        'actions' => '操作',
        'reveal' => '显示',
        'revoked' => '已吊销',
        'active' => '活跃',
        'revoke' => '吊销',
        'rotate' => "重置",
        'noactions' => '无法操作',
        'wechat2fa' => '微信两步验证',
        'createat' => '创建于',
        'banned' => '已封禁',
        'frozen' => '已冻结',
        'audit' => '审计',
        'create_client' => '签发了新的Client',
        'revoke_client' => '吊销了一个Client',
        'rotate_clisec' => '重置了一个Client',
        'adminactivity' => '管理员日志',
        'useractivity' => '用户日志',
        'unban' => '解除封禁',
        'unfro' => '解冻',
        'more' => '更多',
        'sureaboutbanuser' => '确定要封禁此用户吗',
        'sureaboutunbanuser' => '确定要解封此用户吗',
        'sureaboutunfrouser' => '确定要协助此用户解冻吗',
        'ban' => '封禁',
        'unfro_user' => "解冻了一个用户",
        'unban_user' => '解封了一个用户',
        'ban_user' => '封禁了一个用户',
        'secset' => "安全设置",
        'linkwechat' => "绑定微信",
        'enabled' => "已启用",
        'enable' => "点击启用",
        'disable' => "点击禁用",
        'disabled' => "已禁用",
        'enterverificationcodetodisable' => '输入验证码以禁用',
        'emailloginlog' => "登录提醒邮件",
        'enabledwechat2fa' => '微信两步验证已开启',
        'disabledwechat2fa' => '微信两步验证已禁用',
        'updateemailsuccessbutneedverify' => '更新完成，请重新验证邮箱。',
        'cantturnoff2fa' => '验证失败，无法关闭两步验证。',
        'youremailisnotverified' => '尚未验证邮箱所有权',
        'clicktoverify' => '点击验证',
        'changed' => '已修改',
        'old' => '旧',
        'new' => '新',
        'invalidusername' => '无效的用户名',
        'lengthmustbe' => '长度应该为',
        'revokeallpasskey' => '撤销所有Passkey',
        'addpasskey' => '添加Passkey',
        'loginwithpasskey' => '通过Passkey登录',
        'passkeyadded' => '已添加新的Passkey',
        'allpasskeyrevoked' => '所有Passkey已被撤销',
        'removeduserpasskey' => '删除了用户的Passkey',
        'mustbindwechat' => '强制微信',
        'wechatbindenforced' => '你所登录的站点已强制所有用户绑定微信',
        'verificationcodeexpired' => "验证码已过期，请重新申请",
        'verificationcodesent' => '验证码已发送至您的邮箱，请查收',
        'requestverificationcode' => '请求验证码',
    ];
}

function enus() {
    return [
        'username' => 'Username',
        'password' => 'Password',
        'login' => 'Login',
        'logout' => 'Sign out',
        'logout_all' => 'REVOKE ALL ACCESS & Sign out',
        'accountsettings' => 'Acc. Settings',
        'email' => 'Email',
        'phonenumber' => 'Phone Number',
        'optional' => 'Optional',
        'register' => 'Register',
        'verifyemail' => 'Verify your email',
        'verificationcode' => 'Verification code',
        'submit' => 'Submit',
        'noaccount' => "Don't have an account yet?",
        'haveacc' => 'Already have an account?',
        'warning' => 'Warning',
        'invalidcredential' => 'Your credential is not valid',
        'emergencyblock' => "Lockdown your account",
        'notification' => 'Notification',
        'notifications' => 'Notifications',
        'loginsuccessful' => 'Successful login',
        'passwordchanged' => 'Password changed',
        'idchanged' => 'ID changed',
        'emailchanged' => 'Email changed',
        'phonenumberchanged' => 'Phone number changed',
        'contactadmintoedit' => 'Please contact the admin to change this scope',
        'notchanged' => 'Not Changed',
        'adminportal' => 'Admin Portal',
        '2fa' => '2FA CODE',
        'errortitle' => 'Oops… You just found an error',
        'PKCE_required' => 'Seems you have to click LOGIN again at the third party site',
        'totheportal' => 'Take me to the portal',
        'wechatcode' => 'WeChat Code',
        'wechat2farequired' => 'Your account has enabled 2FA via WeChat, please enter your WeChat Code properly.',
        'learnmore' => 'Learn More',
        'dashboard' => 'Dashboard',
        'clientcontrol' => 'Client Controller',
        'systemutil' => 'System Utilities',
        'usercontrol' => 'User Controller',
        'mgmt' => 'Management',
        'createnewclient' => 'Create New Client',
        'requirepkce' => 'Require PKCE',
        'create' => 'Create',
        'oneperline' => 'One per line',
        'registeredclients' => 'Registered Clients',
        'status' => 'Status',
        'actions' => 'Actions',
        'reveal' => 'Reveal',
        'revoked' => 'Revoked',
        'active' => 'Active',
        'revoke' => 'REVOKE',
        'rotate' => "Rotate",
        'noactions' => 'No actions',
        'wechat2fa' => 'WeChat 2FA',
        'createat' => 'Created at',
        'banned' => 'Banned',
        'frozen' => 'Lockdown',
        'audit' => 'Audit',
        'create_client' => 'Created a client',
        'revoke_client' => 'Revoked a client',
        'rotate_clisec' => 'Rotated a client',
        'adminactivity' => 'Admin Activity',
        'useractivity' => 'User Activity',
        'unban' => 'Unban',
        'unfro' => 'Unlock',
        'more' => 'More',
        'sureaboutbanuser' => 'Ban this user?',
        'sureaboutunbanuser' => 'Unbanned this user?',
        'sureaboutunfrouser' => 'Unlock this user?',
        'ban' => 'BAN',
        'unfro_user' => "Unlocked a user",
        'unban_user' => 'Unbanned a user',
        'ban_user' => 'Banned a user',
        'secset' => "Security Settings",
        'linkwechat' => "Bind your WeChat account",
        'enabled' => "Enabled",
        'enable' => "Enable",
        'disable' => "Disable",
        'disabled' => "Disabled",
        'enterverificationcodetodisable' => 'Enter the verification code to disable',
        'emailloginlog' => "Login notification via Email",
        'enabledwechat2fa' => 'Enabled WeChat 2fa',
        'disabledwechat2fa' => 'Disabled WeChat 2fa',
        'updateemailsuccessbutneedverify' => 'Email updated! Please re-verify your email address.',
        'cantturnoff2fa' => 'Authentication failed, 2fa is still on.',
        'youremailisnotverified' => "You havn't verified your email yet",
        'clicktoverify' => 'Click here to verify',
        'changed' => 'Changed',
        'old' => 'Old',
        'new' => 'New',
        'invalidusername' => 'Invalid Username',
        'lengthmustbe' => 'Length must be',
        'revokeallpasskey' => 'Revoke All Passkey(s)',
        'addpasskey' => 'Add Passkey',
        'loginwithpasskey' => 'Logged in with Passkey',
        'passkeyadded' => 'Passkey was added',
        'allpasskeyrevoked' => 'All Passkey(s) has been revoked',
        'removeduserpasskey' => 'Removed User Passkey',
        'mustbindwechat' => 'Must Bind WeChat',
        'wechatbindenforced' => 'The app you are trying to sign in has enforced everyone to bind a WeChat account',
        'verificationcodeexpired' => "Your verification code has expired, please request a new one",
        'verificationcodesent' => 'Your verification code was sent',
        'requestverificationcode' => 'Request your verification code',
    ];
}
